import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { SocketProvider } from "../../context/SocketProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SocketProvider>
      <GoogleOAuthProvider clientId="726588190910-luueofnjugovsifaqqm4j3sokqp4a3hh.apps.googleusercontent.com">
      <body className={inter.className}>{children}</body>
      </GoogleOAuthProvider>
      </SocketProvider>
    </html>
  );
}
